package auth

import (
	"context"
	"errors"
	"os"
	"testing"

	"github.com/jackc/pgx/v5/pgxpool"
)

func TestIdentityIsCurrent(t *testing.T) {
	cached := Identity{UserID: 7, ClassID: 9, SID: "20260001", Role: "group", TokenVersion: 3}
	tests := []struct {
		name    string
		current Identity
		status  string
		want    bool
	}{
		{name: "current", current: cached, status: "active", want: true},
		{name: "disabled", current: cached, status: "disabled"},
		{name: "different user", current: Identity{UserID: 8, ClassID: 9, Role: "group", TokenVersion: 3}, status: "active"},
		{name: "different class", current: Identity{UserID: 7, ClassID: 10, Role: "group", TokenVersion: 3}, status: "active"},
		{name: "role changed", current: Identity{UserID: 7, ClassID: 9, Role: "student", TokenVersion: 3}, status: "active"},
		{name: "token revoked", current: Identity{UserID: 7, ClassID: 9, Role: "group", TokenVersion: 4}, status: "active"},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			if got := identityIsCurrent(cached, test.current, test.status); got != test.want {
				t.Fatalf("identityIsCurrent() = %v, want %v", got, test.want)
			}
		})
	}
}

func TestActivateAfterAdminPasswordReset(t *testing.T) {
	for _, status := range []string{"active", "disabled"} {
		t.Run(status, func(t *testing.T) {
			url := os.Getenv("EASYGPA_TEST_DATABASE_URL")
			if url == "" {
				t.Skip("set EASYGPA_TEST_DATABASE_URL to run registration database tests")
			}
			cfg, err := pgxpool.ParseConfig(url)
			if err != nil {
				t.Fatal(err)
			}
			// One connection keeps temporary tables scoped to this test while
			// exercising activate's real transaction and commit behavior.
			cfg.MaxConns = 1
			pool, err := pgxpool.NewWithConfig(t.Context(), cfg)
			if err != nil {
				t.Fatal(err)
			}
			t.Cleanup(pool.Close)
			_, err = pool.Exec(t.Context(), `
			 CREATE TEMP TABLE whitelist (id bigint PRIMARY KEY, registered_at timestamptz, active boolean, role text, updated_at timestamptz);
			 CREATE TEMP TABLE app_user (
			  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, class_id bigint,
			  whitelist_id bigint UNIQUE, sid text, name text, password_hash text, role text,
			  status text DEFAULT 'active', token_version bigint DEFAULT 1, updated_at timestamptz,
			  is_deputy boolean NOT NULL DEFAULT false
			 );
			 CREATE TEMP TABLE user_email (user_id bigint, verified_at timestamptz);
			 CREATE TEMP TABLE class (id bigint PRIMARY KEY, name text);
			 CREATE TEMP TABLE audit_log (class_id bigint, actor_id bigint, actor_role text, action text, resource_type text, resource_id text, metadata jsonb);
			 INSERT INTO whitelist VALUES (8,NULL,true,'group',now());
			 INSERT INTO app_user (id,class_id,whitelist_id,sid,name,password_hash,role,token_version)
			 VALUES (7,9,8,'test-7','Existing member',NULL,'group',4);
			 INSERT INTO user_email VALUES (7,'2026-01-01 UTC');
			 INSERT INTO class VALUES (9,'Test class');
			`)
			if err != nil {
				t.Fatal(err)
			}
			if _, err := pool.Exec(t.Context(), `UPDATE app_user SET status=$1 WHERE id=7`, status); err != nil {
				t.Fatal(err)
			}
			service := &Service{db: pool}
			identity, _, err := service.activate(t.Context(), pendingRegistration{
				ClassID: 9, WhitelistID: 8, SID: "test-7", Name: "Existing member", Role: "group", PasswordHash: "new-hash",
			})
			if status == "disabled" {
				if !errors.Is(err, ErrAccountDisabled) {
					t.Fatalf("activation error=%v, want account disabled", err)
				}
			} else if err != nil {
				t.Fatal(err)
			} else if identity.UserID != 7 || identity.Role != "group" || identity.TokenVersion != 5 {
				t.Fatalf("activation replaced identity or role: %+v", identity)
			}
			var passwordSet, registered bool
			var role, actualStatus string
			var emailCount, userCount int
			err = pool.QueryRow(context.Background(), `
			 SELECT u.password_hash IS NOT NULL,w.registered_at IS NOT NULL,u.role,u.status,
			        (SELECT count(*) FROM user_email WHERE user_id=7),(SELECT count(*) FROM app_user)
			 FROM app_user u JOIN whitelist w ON w.id=u.whitelist_id WHERE u.id=7
			`).Scan(&passwordSet, &registered, &role, &actualStatus, &emailCount, &userCount)
			if err != nil {
				t.Fatal(err)
			}
			if passwordSet != (status == "active") || registered != (status == "active") || role != "group" || actualStatus != status || emailCount != 1 || userCount != 1 {
				t.Fatalf("activation changed protected state: password=%v registered=%v role=%s status=%s emails=%d users=%d", passwordSet, registered, role, actualStatus, emailCount, userCount)
			}
		})
	}
}
