// Package objectstore is the narrow S3 boundary used with Garage. Every key is
// generated by the backend; callers never supply an arbitrary object path.
package objectstore

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net/url"
	"strings"
	"time"

	"github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/cors"
	"github.com/minio/minio-go/v7/pkg/credentials"
)

type Config struct {
	Endpoint       string
	PublicEndpoint string
	Region         string
	AccessKey      string
	SecretKey      string
	Bucket         string
	UseSSL         bool
	// PublicUseSSL controls only the scheme of presigned URLs. Behind a public
	// HTTPS entry point the browser must be handed https:// links, while the
	// in-cluster connection to Garage stays plain HTTP. One shared flag cannot
	// express that, and mixed-content rules make "just leave it http" a dead end.
	PublicUseSSL bool
}

type Client struct {
	s3        *minio.Client
	presigner *minio.Client
	bucket    string
}

func New(cfg Config) (*Client, error) {
	if cfg.Endpoint == "" || cfg.AccessKey == "" || cfg.SecretKey == "" || cfg.Bucket == "" {
		return nil, errors.New("S3 endpoint, credentials and bucket are required")
	}
	s3, err := minio.New(cfg.Endpoint, &minio.Options{
		Creds: credentials.NewStaticV4(cfg.AccessKey, cfg.SecretKey, ""), Secure: cfg.UseSSL, Region: cfg.Region,
	})
	if err != nil {
		return nil, err
	}
	publicEndpoint := cfg.PublicEndpoint
	if publicEndpoint == "" {
		publicEndpoint = cfg.Endpoint
	}
	presigner, err := minio.New(publicEndpoint, &minio.Options{
		Creds: credentials.NewStaticV4(cfg.AccessKey, cfg.SecretKey, ""), Secure: cfg.PublicUseSSL, Region: cfg.Region,
	})
	if err != nil {
		return nil, err
	}
	return &Client{s3: s3, presigner: presigner, bucket: cfg.Bucket}, nil
}

// EnsureCORS 让浏览器能直传附件。
//
// 佐证是浏览器拿预签名 policy 直接 POST 到对象存储的,跨了源(端口不同就算跨源),
// 而 multipart POST 会触发预检 —— Garage 默认不带任何 CORS 规则,预检直接 403。
// 这个坑测不出来:端到端冒烟跑在 Node 里,Node 没有同源策略。
//
// 规则写死在这里而不是做成配置:允许哪些源是部署形态决定的,
// 传进来的是 PUBLIC_URL 一类已经存在的值,再开一个开关只会多一处能配错的地方。
func (c *Client) EnsureCORS(ctx context.Context, origins []string) error {
	rules := corsRules(origins)
	if len(rules) == 0 {
		return nil
	}
	return c.s3.SetBucketCors(ctx, c.bucket, cors.NewConfig(rules))
}

func corsRules(origins []string) []cors.Rule {
	rules := make([]cors.Rule, 0, len(origins))
	seen := make(map[string]struct{}, len(origins))
	for _, origin := range origins {
		origin = strings.TrimSpace(origin)
		if origin == "" {
			continue
		}
		if _, exists := seen[origin]; exists {
			continue
		}
		seen[origin] = struct{}{}

		// Garage 2.x 会把同一条规则里的多个 AllowedOrigin 全部写进
		// Access-Control-Allow-Origin，浏览器会因响应头含多个值而拒绝。
		// 每个来源单独一条规则，预检只匹配并回显请求对应的来源。
		rules = append(rules, cors.Rule{
			AllowedOrigin: []string{origin},
			AllowedMethod: []string{"GET", "POST", "HEAD"},
			AllowedHeader: []string{"*"},
			// 直传要读 ETag 来核对文件是否完整落盘
			ExposeHeader:  []string{"ETag", "Content-Range", "Accept-Ranges", "Retry-After"},
			MaxAgeSeconds: 3600,
		})
	}
	return rules
}

func (c *Client) Ready(ctx context.Context) error {
	exists, err := c.s3.BucketExists(ctx, c.bucket)
	if err != nil {
		return err
	}
	if !exists {
		return fmt.Errorf("S3 bucket %q does not exist", c.bucket)
	}
	return nil
}

type UploadPolicy struct {
	URL    *url.URL
	Fields map[string]string
}

// PresignUpload binds the object key, exact byte length and media type into an
// S3 POST policy. A plain presigned PUT cannot cap bytes and would let a caller
// declare a small file while filling the object-store volume with a huge one.
func (c *Client) PresignUpload(ctx context.Context, key, mediaType string, size int64, expires time.Duration) (UploadPolicy, error) {
	if key == "" || mediaType == "" || size <= 0 || expires <= 0 {
		return UploadPolicy{}, errors.New("upload policy requires key, media type, size and positive expiry")
	}
	policy := minio.NewPostPolicy()
	for _, err := range []error{
		policy.SetBucket(c.bucket),
		policy.SetKey(key),
		policy.SetExpires(time.Now().UTC().Add(expires)),
		policy.SetContentLengthRange(size, size),
		policy.SetContentType(mediaType),
	} {
		if err != nil {
			return UploadPolicy{}, err
		}
	}
	target, fields, err := c.presigner.PresignedPostPolicy(ctx, policy)
	if err != nil {
		return UploadPolicy{}, err
	}
	return UploadPolicy{URL: target, Fields: fields}, nil
}

// PresignGet issues a temporary read URL. inline lets the browser render the
// object in place instead of downloading it; callers must restrict that to
// content types the browser can display safely.
func (c *Client) PresignGet(ctx context.Context, key string, expires time.Duration, filename string, inline bool) (*url.URL, error) {
	params := make(url.Values)
	if filename != "" {
		disposition := "attachment"
		if inline {
			disposition = "inline"
		}
		params.Set("response-content-disposition", disposition+`; filename*=UTF-8''`+url.PathEscape(filename))
	}
	return c.presigner.PresignedGetObject(ctx, c.bucket, key, expires, params)
}

type ObjectInfo struct {
	Size        int64
	ContentType string
	ETag        string
}

type ListedObject struct {
	Key  string
	Size int64
}

func (c *Client) List(ctx context.Context) ([]ListedObject, error) {
	return c.ListPrefix(ctx, "")
}

func (c *Client) ListPrefix(ctx context.Context, prefix string) ([]ListedObject, error) {
	items := make([]ListedObject, 0)
	for item := range c.s3.ListObjects(ctx, c.bucket, minio.ListObjectsOptions{Recursive: true, Prefix: prefix}) {
		if item.Err != nil {
			return nil, item.Err
		}
		items = append(items, ListedObject{Key: item.Key, Size: item.Size})
	}
	return items, nil
}

func (c *Client) Stat(ctx context.Context, key string) (ObjectInfo, error) {
	info, err := c.s3.StatObject(ctx, c.bucket, key, minio.StatObjectOptions{})
	if err != nil {
		return ObjectInfo{}, err
	}
	return ObjectInfo{Size: info.Size, ContentType: info.ContentType, ETag: info.ETag}, nil
}

func (c *Client) Remove(ctx context.Context, key string) error {
	return c.s3.RemoveObject(ctx, c.bucket, key, minio.RemoveObjectOptions{})
}

func (c *Client) Put(ctx context.Context, key, mediaType string, reader io.Reader, size int64) error {
	_, err := c.s3.PutObject(ctx, c.bucket, key, reader, size, minio.PutObjectOptions{ContentType: mediaType})
	return err
}

// Copy creates an independent object for a submission evidence row. AI batch
// assets remain immutable audit inputs, while each resulting draft owns its
// normal evidence object and can therefore be deleted without breaking another
// draft that happened to reference the same source PDF.
func (c *Client) Copy(ctx context.Context, sourceKey, destinationKey, mediaType string, size int64) error {
	reader, err := c.Open(ctx, sourceKey)
	if err != nil {
		return err
	}
	defer reader.Close()
	return c.Put(ctx, destinationKey, mediaType, reader, size)
}

func (c *Client) Open(ctx context.Context, key string) (io.ReadCloser, error) {
	object, err := c.s3.GetObject(ctx, c.bucket, key, minio.GetObjectOptions{})
	if err != nil {
		return nil, err
	}
	// GetObject is lazy; Stat forces an authorization/existence check before the
	// caller starts streaming bytes into an archive.
	if _, err := object.Stat(); err != nil {
		_ = object.Close()
		return nil, err
	}
	return object, nil
}
